package.json
Describe the changes made in your pull request here.
=> chore: fix repo name in package.json

src/RewardsStreamerMP.sol, test/RewardsStreamerMP.t.sol
=> test: add tests for reaching MP limit

certora/specs/RewardsStreamerMP.spec
=> chore(certora): add rule that greater lockup means greater MPs

certora/confs/StakeVault.conf, certora/specs/RewardsStreamerMP.spec, certora/specs/StakeVault.spec, certora/specs/shared.spec
=> chore(certora): formally verify `StakeVault` account balance vs ERC20

test/StakeVault.test.sol
Describe the changes made in your pull request here.
=> test(StakeVault): introduce test file for `StakeVault`

certora/specs/RewardsStreamerMP.spec
=> test: formally verify that MPs only decrease when unstaking/leaving

docs/multiplier-points.md
=> chore(docs/multiplier-points.md): Add guide to multiplier poitns

docs/rewards.md
=> docs(rewards): add documentation about how rewards work

docs/xp-token.md
This PR adds documentation about the XP Token.
closes #36
=> docs(XPToken): add documentation about the XP Token

src/RewardsStreamerMP.sol
=> refactor(RewardsStreamerMP): reuse modifier in `enableEmergencyMode()`

.github/workflows/ci.yml
=> ci: update certora CLI to 7.25.2

src/StakeVault.sol, src/TransparentProxy.sol, src/TrustedCodehashAccess.sol, src/VaultFactory.sol, src/interfaces/IRewardProvider.sol, src/interfaces/IStakeConstants.sol, src/interfaces/IStakeManager.sol, src/interfaces/ITransparentProxy.sol
=> docs(StakeVault): complete natspec comments

script/DeploymentConfig.s.sol, src/RewardsStreamerMP.sol, test/KarmaNFT.t.sol, test/RewardsStreamerMP.t.sol, test/StakeVault.test.sol, test/mocks/KarmaDistributorMock.sol
=> cleanup: address linter warnings

.prettierignore, README.md
=> docs(README): add sepolia deployment addresses

certora/confs/MPLessEqualMaxMP.conf, certora/confs/RewardsStreamerMP.conf, package.json
=> fix(certora): fix timeout on certora with specific config

certora/confs/RewardsStreamerMP.conf
=> refactor(specs): exclude rule instead of including other rules

.github/workflows/ci.yml
=> fix(ci): run MPLessEqualMaxMP spec on CI

certora/specs/Karma.spec
Ensure totalDistributorAllocation can only increase
=> test(certora): Karma.totalDistributorAllocation can only increase

.prettierignore, CHANGELOG.md, package.json
=> chore(release): 0.1.1

src/Karma.sol, src/KarmaNFT.sol, src/RewardsStreamerMP.sol, src/StakeVault.sol, src/TransparentProxy.sol, src/TrustedCodehashAccess.sol, src/VaultFactory.sol, src/interfaces/INFTMetadataGenerator.sol, src/interfaces/IRewardDistributor.sol, src/interfaces/IStakeConstants.sol, src/interfaces/IStakeManager.sol, src/interfaces/IStakeManagerProxy.sol, src/interfaces/IStakeVault.sol, src/interfaces/ITransparentProxy.sol, src/interfaces/ITrustedCodehashAccess.sol, src/math/MultiplierPointMath.sol, src/math/StakeMath.sol
This is to avoid running into bugs in the future, in case the compiler introduces one in the version range that was specified before.
=> cleanup: specify exact compiler version

CHANGELOG.md, package.json
=> chore(release): 0.2.0

CHANGELOG.md, package.json
=> chore(release): 0.2.1

test/Karma.t.sol
slash
This will otherwise find counter examples where the transaction reverts.
=> test(Karma): adjust fuzz test for slashing to ensure there's balance to
